version: '3.8'
services:
  hrls-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=hrlsdb
      - MYSQL_USER=hrls
      - MYSQL_PASSWORD=hrls
      - MYSQL_ROOT_PASSWORD=hrls-root
    ports:
      - "3307:3306"
    volumes:
      - hrls-mysql-data:/var/lib/mysql
      - ./api/src/main/resources/db/hrls/V1.0__prefixes.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  hrls-mysql-data:
      driver: local

