<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>gr.grnet</groupId>
    <artifactId>pcc</artifactId>
    <packaging>pom</packaging>
    <name>pcc</name>
    <version>${revision}</version>

    <modules>
        <module>api</module>
        <module>connectors</module>
        <module>daemons</module>
    </modules>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <!-- Quarkus -->
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.version>3.27.0</quarkus.platform.version>

        <!-- Plugins -->
        <compiler-plugin.version>3.15.0</compiler-plugin.version>
        <surefire-plugin.version>3.5.5</surefire-plugin.version>
        <spotless.maven.plugin.version>2.43.0</spotless.maven.plugin.version>
        <checkstyle.maven.plugin.version>3.3.1</checkstyle.maven.plugin.version>
        <checkstyle.puppycrawl.version>10.12.5</checkstyle.puppycrawl.version>
        <mysql.connector.version>9.1.0</mysql.connector.version>
        <hikari.version>5.1.0</hikari.version>

        <!-- Libraries -->
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <lombok.version>1.18.30</lombok.version>
        <apache.commons3.version>3.17.0</apache.commons3.version>
        <wiremock.version>3.13.2</wiremock.version>
        <httpclient5.version>5.4.4</httpclient5.version>
        <quartz.version>2.5.2</quartz.version>
        <picocli.version>4.7.7</picocli.version>
        <junit.version>4.13.2</junit.version>
        <logging.version>3.6.3.Final</logging.version>
        <quarkus-auth.version>1.0.1-SNAPSHOT</quarkus-auth.version>
        <jandex.version>3.5.0</jandex.version>
        <keycloak.module.dir>${maven.multiModuleProjectDirectory}/keycloak</keycloak.module.dir>
    </properties>

    <repositories>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/ARGOeu/quarkus-auth</url>
        </repository>
    </repositories>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${apache.commons3.version}</version>
            </dependency>
            <dependency>
                <groupId>org.grnet</groupId>
                <artifactId>quarkus-auth</artifactId>
                <version>${quarkus-auth.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- Quarkus plugin -->
                <plugin>
                    <groupId>${quarkus.platform.group-id}</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.platform.version}</version>
                    <extensions>true</extensions>
                    <executions>
                        <execution>
                            <goals>
                                <goal>build</goal>
                                <goal>generate-code</goal>
                                <goal>generate-code-tests</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <!-- Java compiler -->
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${compiler-plugin.version}</version>
                    <configuration>
                        <compilerArgs>
                            <arg>-parameters</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>

                <!-- Unit testing -->
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                    <configuration>
                        <systemPropertyVariables>
                            <!-- Fix the early LogManager warning -->
                            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>

                <!-- Jandex indexing for Quarkus -->
                <plugin>
                    <groupId>io.smallrye</groupId>
                    <artifactId>jandex-maven-plugin</artifactId>
                    <version>${jandex.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>jandex</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>