package gr.grnet.pccapi.dto;

import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A class that represents a Provider served as response by the Provider endpoint */
@Schema(
    name = "ProviderResponse",
    description = "Provider is an organisation that hosts the handle service")
public class ProviderResponseDTO {
  @Schema(
      type = SchemaType.INTEGER,
      implementation = Integer.class,
      description = "The unique provider id generated by the database.",
      example = "1")
  public int id;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The name of the provider .",
      example = "GRNET")
  public String name;

  public int getId() {
    return id;
  }

  public String getName() {
    return name;
  }
}
