package gr.grnet.pccapi.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;


/**
 * DTO class for the service domain resource
 */
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Schema(
        name="ServiceResponse",
        description="Represents one of the possible services that are registered in the service"
)
public class ServiceDto {
    @Schema(
            type = SchemaType.INTEGER,
            implementation = Integer.class,
            description = "The unique service id generated by the database.",
            example = "1"
    )
    public Integer id;
    @Schema(
            type = SchemaType.STRING,
            implementation = String.class,
            description = "The Service name.",
            example = "B2HANDLE"
    )
    public String name;
}
