# configure your datasource
quarkus.datasource.db-kind=mysql
%prod.quarkus.datasource.username=root
%prod.quarkus.datasource.password=secret
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/pccdb
quarkus.hibernate-orm.sql-load-script = no-file

# datasource development configuration

%dev.quarkus.datasource.devservices.port=3306
%dev.quarkus.datasource.devservices.db-name=pccdb
%dev.quarkus.datasource.devservices.username=pcc
%dev.quarkus.datasource.devservices.password=pcc
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.datasource.devservices.volumes."classpath\:db/mysql/devservices-init.sql"=/docker-entrypoint-initdb.d/00-init.sql

%test.quarkus.datasource.devservices.port=3307
%test.quarkus.datasource.devservices.db-name=pccdb
%test.quarkus.datasource.devservices.username=pcc
%test.quarkus.datasource.devservices.password=pcc
%test.quarkus.datasource.devservices.volumes."classpath\:db/mysql/devservices-init.sql"=/docker-entrypoint-initdb.d/00-init.sql
%test.quarkus.datasource.devservices.reuse=false

quarkus.rest-client."gr.grnet.pccapi.client.hrls.HRLSClient".url=https://hdl2.grnet.gr:8004

cron.expr=0 0 0 * * ?
daemon.cron.expr=0 0 * * * ?
quarkus.rest.path=api/v1

quarkus.http.cors.enabled=false
%dev.quarkus.http.cors.origins=/.*/

# flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0

# swagger
quarkus.smallrye-openapi.path=/open-api
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.info-title=PID Central Catalogue - PCC-API
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=PID Central Catalogue: A place where all Prefixes are described and allo Handles are indexed for search and reverse-lookup.
quarkus.smallrye-openapi.info-terms-of-service=Your terms here
quarkus.smallrye-openapi.info-contact-email=info@einfra.grnet.gr
quarkus.smallrye-openapi.info-contact-name=GRNET eINFRA Development Team
#quarkus.smallrye-openapi.info-contact-url=http://exampleurl.com/contact
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

# ---------------------------------------------------------
# OpenID Connect (OIDC / Keycloak)
# ---------------------------------------------------------

# Local Keycloak started through Compose Dev Services
%dev.quarkus.oidc.auth-server-url=http://localhost:58080/realms/rciam
%test.quarkus.oidc.auth-server-url=http://localhost:58080/realms/rciam
%prod.quarkus.oidc.auth-server-url=https://login-devel.einfra.grnet.gr/auth/realms/einfra
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.authorization-path=/protocol/openid-connect/auth
quarkus.oidc.token-path=/protocol/openid-connect/token
quarkus.oidc.discovery-enabled=false
quarkus.oidc.introspection-path=/protocol/openid-connect/token/introspect
%prod.quarkus.oidc.user-info-path=/protocol/openid-connect/userinfo
%prod.quarkus.oidc.authentication.user-info-required=true

quarkus.keycloak.devservices.enabled=false
%dev.quarkus.compose.devservices.files=../keycloak/docker-compose.yml
%dev.quarkus.compose.devservices.project-name=keycloak-local

# ---------------------------------------------------------
# Custom claim for unique user ID
# ---------------------------------------------------------
api.auth.oidc.user.unique.id=voperson_id

# ---------------------------------------------------------
# Keycloak Group Management (Auth Library Integration)
# ---------------------------------------------------------
# REST clients for AAI Group Management
api.auth.entitlements.keycloak-group-management-client-url=http://localhost:58080/realms/rciam/
api.auth.entitlements.keycloak-group-management-client-id=status.page.manage.groups
api.auth.entitlements.keycloak-group-management-client-secret=nlKena9eYtF7XMeP8kZD0YU9pStxPggN

# Keycloak User Entitlements
%dev.api.auth.entitlements.parent-group=pcc-api
%test.api.auth.entitlements.parent-group=pcc-api
%prod.api.auth.entitlements.parent-group=pcc-api
%dev.api.auth.entitlements.namespace=urn:rciam.example.org
%test.api.auth.entitlements.namespace=urn:rciam.example.org
%prod.api.auth.entitlements.namespace=urn:mace:grnet.gr:einfra:login-devel
%test.api.auth.entitlements.super-admin-role=super_admin
%dev.api.auth.entitlements.super-admin-role=super_admin
%prod.api.auth.entitlements.super-admin-role=super_admin

# ---------------------------------------------------------
# HTML / OIDC UI Integration (Qute template)
# ---------------------------------------------------------
# keycloak properties for feeding the oidc_client html template
api.html.keycloak.url=http://localhost:58080
api.html.keycloak.realm=rciam
api.html.keycloak.public.client.id=frontend-service
api.html.keycloak.javascript.adapter=/js/keycloak.min.js
api.html.oidc.client.url=http://localhost:8080/api/v1/oidc-client
api.html.swagger.documentation=http://localhost:8080/swagger-ui