package gr.grnet.pccapi.dto;

import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Getter
@Setter
@Accessors(chain = true)
@Schema(name = "Prefix")
public class CodelistDto {
  @Schema(
      type = SchemaType.INTEGER,
      implementation = Integer.class,
      description = "The unique Domain ID generated by the database.",
      example = "1")
  public Integer id;

  @NotNull public String name;
  @NotNull public String category;
}
