package gr.grnet.pccapi.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(
    name = "ScientificDomainResponse",
    description =
        "Scientific Domain is the branch of science,"
            + " scientific discipline that is related to the project using the Prefix."
            + " It uses the Classification Information/Scientific Domain from EOSC Profiles.")
public class DomainDto {

  @Schema(
      type = SchemaType.INTEGER,
      implementation = Integer.class,
      description = "The unique Domain ID generated by the database.",
      example = "1")
  public Integer id;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description =
          "The Domain ID retrieved and generated by EOSC via the EOSC Providers Portal (described in EOSC Profiles).",
      example = "scientific_domain-engineering_and_technology")
  @JsonProperty("domain_id")
  public String domainId;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The Domain name.",
      example = "Engineering & Technology")
  public String name;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The Domain description.",
      example =
          "The application of science and mathematics by which the properties of matter and the sources of energy"
              + " in nature are made useful to people")
  public String description;
}
