package gr.grnet.pccapi.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Getter
@Schema(name = "PrefixResponse")
public class PrefixResponseDto extends PrefixDto {

  @Schema(
      type = SchemaType.INTEGER,
      implementation = Integer.class,
      description = "The unique Prefix ID generated by the database.",
      example = "1")
  public Integer id;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The name of the linked service.",
      example = "1")
  @JsonProperty("service_name")
  public String serviceName;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The name of the linked domain.",
      example = "1")
  @JsonProperty("domain_name")
  public String domainName;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The name of the linked provider.",
      example = "1")
  @JsonProperty("provider_name")
  public String providerName;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The name of the contract type.",
      example = "1")
  @JsonProperty("contract_type_name")
  public String contractTypeName;

  @Schema(
      type = SchemaType.STRING,
      implementation = String.class,
      description = "The name of the lookup service.",
      example = "NONE")
  @JsonProperty("lookup_service_type_name")
  public String lookUpServiceName;
}
